### ISSUE TITLE
How to use it in NextJS

### ISSUE THREAD

**Issue by bigomise** [TypeFox/monaco-editor-workers#1]
Hi,

I'm interested in this this package and I have found this package from Langium but i'm not sure how to use it with NextJS.

Could I ask for an example, please?

Thank you in advance!

**Comment by kaisalmen** [comment]
Hi @bigomise are you aware of this react example?
https://github.com/TypeFox/monaco-components/blob/main/packages/examples/src/reactTs.tsx

Basically you need to specify a valid URL where monaco-editor can load its workers from. This is framework independent.
